sudo: required
language: java
notifications:
  email: false
jdk:
- oraclejdk11
services:
- docker
script:
- ".travis/build.sh $VERSION $COMMIT"
env:
  global:
  - VERSION=11-1
  - COMMIT=${TRAVIS_COMMIT::8}
  matrix:
  - secure: MTUYhnTpRnQxS8sMxUY9hOZOIK4ArG3Ghgke6NFZ6Lsg8pg9JShX/nbO8WdLU+yGgd5ku2fE1nbrlJpu22BJdhRT+TLVFOVy55ZOe080sEVzoJisvQsQpfJmMOcoOKRZ8fqQxd55dyV3EpAgnOVLDk6oci31R4k9m7I4LLPsa6bw4V7xJqFjmGi7EJEgWwC8lQmMXUCHQkWMSH6+8Caux9wEQRdIWUynmVB+dbEfnR1xuX8nhuazuQmbiy6E5/6b7EumiVCdDqXhbO4DT9DIeYJZ7B9NoX9YlTn+MvNNU6pStGadhyKzD2ECs7wwrsdUU7gboPVsyhkI2mHFSbn/CyLCXsf2zpbsW+cno0HgTnrtOoMIpcZDY0CcTChAkqaoBaWgtMIiYQuR7dgIgn+hDLz8zfFscMmOI5KLbX+OuGL+P7ZboDpavPlCdzBTGvlI991sY3lbLHULPXaW2lv0LKh/PU5C9UUk6LN/F7m2KBUwdoxagmy3L3nDaKtjaxUiOHfjrJJdbKkHNtito9PpGerzOkCP4rbyQhLjUYTr9Boi0UYyhtmsn5fJNL94i3hrgOgzc6tkSnl6KkF2gkAnEdMdxiw1ppTScpJE75GUp/nPqjgu/8Ue8FtiQW5r4pI7KeC+HAGFWpSjBEOBeVmBl3G8L6//khh2kEIUgrBhY5k=
  - secure: REjIbs7KmDDnXxvtp9GGRr03uXf8EJp844avhUhuVKSNw6Pse4CLz8v7Ex34k2i9nsa0N8f9zq3ugvb33XQK6n8+ijW0Afa0rAseJANwX/VLlYCZ4EsX+V7S7xyjmmA47KYZAfr3KeeNybiJ1tE208thufJPN55qNGjuB6P51aiLHE/Td6sIO2UCwUsLEPiadvYJC8kKcspTYZqeYi+CqCQK3WEptwIF52JzXnFHIZGpXjdNySXkTjfiIfxfNKOYWZaWVEj8f5+fiAFDnFeUWr/kXXwsmWrR/kdG2skllJGRi1xKPQIjU4Y/MT/gKWuQ0GeLybjyLBPOgHh5YEbgs575Kdf2RqTi3c4+Gv2CmqQkyz3eEJKcV/Eybg0bhxK0c+ZThoEp1+7lYtTjcDVeDg9cX4FKZY0vzgl/h/DcodLsdKM9eVdJ6UMoolVCn8xjycSnFqy/e2yLl7I4rmdwlLZgC0DSdOM/oppp7BO3R2QixJmRUkWqmKHT8o2LGe/JfAt80P0s0ukT3hd0DaoAlNfXpbH9VDu/b8FRdIwaJMPDpldQuXeBzB8WVK3U1jpL0hyWywISs2vg1Yo17beEQ6ko6/Bh5fbZ3/zJEBoNoZCs6f/7bzzj2kQXYInJA9jz1u/BUz0ydUmaoQdSZsUj41zHXxZRTmebrVkOeapQgIg=
