sudo: required
language: java
dist: xenial
notifications:
  email: false
jdk:
- openjdk11
services:
- docker
script:
- ".travis/build.sh $VERSION $COMMIT"
env:
  global:
  - VERSION=11-4
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: WmKSEXZsjiVsknepnU0rnEMPwbeihIEbHd7vPg78v3XQN7lFejsVq4/jDwUQdkL0UO2kk5IHqYPO67UTkp4wENbRC4VWeGFg/+RskZITtL+tKheS6F2CUSCXKycwO8IwO0nunoIva+B7X7N04/JSXXdDPTacw/0pK88HAzTTX7E+nBwpXpNPO+ORQapHrC0YRgfuAuu19AgMr6H4QsZFfIdNeOuEczR8Dk1qvtoCjUHm6XrdaNgDnGAi0hvBfnJxiC39p58z4eQdBiyKKjAAt1QBFS355Z6zEYQhYeB9Qpyeex2xTCNTWPv8XgG5/xGT6FKxnsgf3OkAppfSFFjZnzojvXXjkjwNKedAsDY4km3ih6cQA8W3sL2QDDAnUTthwhmsk4uGKZBMCfCMByKz6rLeSSsB1cragzWXfvmLkD+Xby6t5Rzxvs39QkzvuTWZxJzYIMCRdoaoPIimc9dnRvSn4XRISejFJhmnEW9E+jBYBK/V4JgmnsdfT6LScp1XUKKmlaDkrCcIaSNBGo7C+Ks3nF2ZxEzwIp3u8dFc0VkfDm9N1VrPw6nEGigM6ayXh2NDAGf2PQ5zY39uBvI9vFmfTm5BTRi1rsB3pULO1X2rkP4ZyeFQWxOT7T9U/TtkhYV7rme6Of1h+GLGjXnyBI26g2OBp3g/363ciThYH/o=
  - secure: HONrmLQMMTuZ8ZFO4Ci4hv68mWC+zWDxFK1qXnkUiMoYoJhX7Y9B/kBggHmfB7pDkmA4Dm7jbv1XTZAma4LRDfBhabfR8XmrST7AZ1Zy+smDIHjxpGz51iXRgHCmZ6dF/BEOyFs27V+Ccy1Pk4ps91hClX3qhmhciYFBt1U4/1tv9mGvcdHmC1BfoVYEMXRQ507sexcdN7cZowmyYmRyWLlxriy3GFDuUNnPjr30OFulj0AVl1HHrWw6ih0W2WuNb4keM4O2sdWx+Q8Uopl4/yMHpP7C/3LqZ7oq3XYFM+hqGj1wS/OBdwgrK5U5qod7IKe2zfvnkUYiKu5/KD3w+DwVzAL/uGAfRDBedrxhJDQV5Gb6r68f/QrlhjVFFqKvPUk76GQrAw3Z4+2lT6vrdWeir0RxQpYYhSeKBVeoEVObMxIiSjQ+4rtOMlla5mkto3QJTnPJhxMqI4fyhEmrjUjch4UMJX9nyo+cPnisGNoZoSKmYnGApPpfuPxmwRdBruuXZvifws4GGohW1mF80YxFg2OWd8WbGEM3TQxzWNljnaBa6xLq69Xyz7r8p4Nx06n7OfdT3g+xaRykBcu0vA6dRh8Nfxb2fayfvPK9WhZElU46tOnovVEzDlD0xdfuLuESyA2qkJWZgLyg+GEwBsr4+3yCpoFr1SuMe55waOo=
